name: escheresque
channels:
  - anaconda
  - conda-forge
  - eelcohoogendoorn
  - clinicalgraphics
  - menpo # fresh mayavi build
dependencies:
  - python
  - numpy
  - numpy-indexed
  - scipy
  - numba
  - openmesh
  - matplotlib
  - vtk
  - qt
  - mayavi
  - traitsui
  - pyface
  - openmesh
  # dev
  # tests
  # visualize
  - pyopengl
  - pip:    # build vispy from master
    - "--editable=git+https://github.com/vispy/vispy.git#egg=vispy-master"