name: escheresque
channels:
  - anaconda
  - eelcohoogendoorn
  - clinicalgraphics
dependencies:
  - python =2.7*
  - numpy
  - numpy-indexed
  - scipy
  - numba
  - openmesh
  - matplotlib
  - vtk
  - qt
  - mayavi
  - traitsui
  - pyface
  - openmesh
  # dev
  - pyyaml =3.11*
  - invoke >=0.11.1,<0.12
  # tests
  - pytest >=2.8.4,<2.9
